# Generated by Django 4.1.3 on 2022-12-16 19:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_user', '0009_profile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ListingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Listing Title')),
                ('price', models.IntegerField(verbose_name='Price (in Rupees)')),
                ('description', models.TextField(verbose_name='Description')),
                ('photo', models.ImageField(upload_to='images')),
                ('sold', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254, verbose_name='Your Email Address')),
                ('phone', models.BigIntegerField(blank=True, null=True, verbose_name='Contact Number (optional)')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.listingtype', verbose_name='Category')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.condition', verbose_name='Item Condition')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.location', verbose_name='Location')),
                ('op', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_user.profile', verbose_name='Owner')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
