# Generated by Django 4.1.3 on 2022-12-17 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='email',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='phone',
        ),
    ]
