# Generated by Django 4.1.3 on 2022-12-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_remove_listing_email_remove_listing_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo',
            field=models.ImageField(upload_to='static/listings/pics'),
        ),
    ]
