# Generated by Django 4.1.3 on 2022-12-13 15:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_user', '0003_school_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canteen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('cooked_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canteen_menu.canteen')),
            ],
        ),
        migrations.CreateModel(
            name='Due',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('canteen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canteen_menu.canteen')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_user.profile')),
            ],
        ),
    ]
