# Generated by Django 4.1.3 on 2022-12-13 04:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, default='', max_length=2048, verbose_name='About'),
        ),
        migrations.AddField(
            model_name='profile',
            name='batch',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Batch'),
        ),
        migrations.AddField(
            model_name='profile',
            name='data',
            field=models.TextField(max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='karma',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='prog',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Program'),
        ),
        migrations.AddField(
            model_name='profile',
            name='upd',
            field=models.BooleanField(default=False),
        ),
    ]
