# Generated by Django 4.1.3 on 2022-12-13 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_menu', '0001_initial'),
        ('my_user', '0003_school_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='courses',
            field=models.ManyToManyField(blank=True, to='my_user.course'),
        ),
        migrations.AddField(
            model_name='profile',
            name='fav_foods',
            field=models.ManyToManyField(blank=True, to='canteen_menu.fooditem'),
        ),
        migrations.AddField(
            model_name='profile',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_user.school'),
        ),
        migrations.AlterField(
            model_name='course',
            name='op',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_user.profile'),
        ),
    ]
