# Generated by Django 4.1.3 on 2022-12-14 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_user', '0004_profile_courses_profile_fav_foods_profile_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dp',
            field=models.ImageField(default='profile_pictures/anonymous.png', upload_to='profile_pictures'),
        ),
    ]
