# Generated by Django 4.1.3 on 2022-12-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_user', '0005_profile_dp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dp',
            field=models.ImageField(default='static/profile_pictures/anonymous.png', upload_to='profile_pictures'),
        ),
    ]
