# Generated by Django 4.1.3 on 2022-12-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_user', '0008_remove_profile_upd_alter_profile_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others'), ('---', '---')], default='---', max_length=16),
        ),
    ]
