# Generated by Django 4.1.3 on 2022-12-15 14:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_user', '0009_profile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('Lost', 'Lost'), ('Found', 'Found')], default='Lost', max_length=200, verbose_name='Lost/Found')),
                ('location', models.CharField(max_length=200)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(max_length=200, verbose_name='Category')),
                ('desc', models.TextField(verbose_name='Description of the Item')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('claimed', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254, verbose_name='Your Email Address')),
                ('submitter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='my_user.profile')),
            ],
            options={
                'ordering': ['-created', '-date'],
            },
        ),
    ]
